version: 2.1

orbs:
  windows: circleci/windows@5.0

jobs:
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    environment:
      BUILD_CONFIGURATION: Release
    steps:
      - checkout
      - run:
          name: "NuGet"
          command: nuget.exe restore EVEMon.sln
      - run:
          name: "Build EVEMon Application"
          command: msbuild -t:build -restore -p:BclBuildImported=Ignore  -p:Configuration=Release EVEMon.sln 
      - run:
          name: "Package EVEMon installer"
          working_directory: ~\project\tools\InstallBuilder\bin\Release
          command: .\EVEMonInstallBuilder.exe
      - store_artifacts:
          path: src\EVEMon\bin\Installbuilder\Installer\
          destination: Installer
      - store_artifacts:
          path: src\EVEMon\bin\Installbuilder\Binaries\
          destination: Binaries
workflows:
  test_and_build:
    jobs:
      - build
